-- CodGenesis: execute este script no SQL Editor do seu projeto Supabase.
-- A senha do usuário deve ser criada em Authentication > Users ou pela API Admin.

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  email text not null unique,
  escola text not null default 'Nao informada',
  escola_id uuid,
  papel text not null default 'aluno' check (papel in ('dono', 'aluno', 'professor', 'gestor_escola')),
  autorizado boolean not null default false,
  criado_em timestamptz not null default now()
);

create table if not exists public.escolas (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique,
  criada_por uuid not null references public.usuarios(id),
  criada_em timestamptz not null default now()
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'usuarios_escola_fk') then
    alter table public.usuarios add constraint usuarios_escola_fk foreign key (escola_id) references public.escolas(id);
  end if;
end $$;

create table if not exists public.progresso (
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  aula_id integer not null,
  concluida boolean not null default false,
  data_conclusao timestamptz,
  primary key (usuario_id, aula_id)
);

create table if not exists public.tarefas (
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  tarefa_id text not null,
  concluida boolean not null default false,
  atualizada_em timestamptz not null default now(),
  primary key (usuario_id, tarefa_id)
);

create table if not exists public.aulas_customizadas (
  id bigint generated by default as identity primary key,
  professor_id uuid not null references public.usuarios(id) on delete cascade,
  trilha_id text not null,
  titulo text not null,
  conteudo text not null,
  criada_em timestamptz not null default now()
);

create table if not exists public.tarefas_customizadas (
  id bigint generated by default as identity primary key,
  professor_id uuid not null references public.usuarios(id) on delete cascade,
  trilha_id text not null,
  texto text not null,
  criada_em timestamptz not null default now()
);

create table if not exists public.comentarios (
  id bigint generated by default as identity primary key,
  aula_id integer not null,
  aluno_id uuid not null references public.usuarios(id) on delete cascade,
  texto text not null check (char_length(texto) between 1 and 1000),
  criado_em timestamptz not null default now()
);

create or replace function public.criar_usuario_perfil()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.usuarios (id, nome, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'nome', split_part(new.email, '@', 1)),
    new.email
  )
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

create or replace function public.usuario_e_dono()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.usuarios where id = auth.uid() and papel = 'dono' and autorizado = true) $$;

drop trigger if exists ao_criar_usuario on auth.users;
create trigger ao_criar_usuario
after insert on auth.users
for each row execute function public.criar_usuario_perfil();

alter table public.usuarios enable row level security;
alter table public.escolas enable row level security;
alter table public.progresso enable row level security;
alter table public.tarefas enable row level security;

drop policy if exists "usuario ve o proprio perfil" on public.usuarios;
create policy "usuario ve o proprio perfil"
on public.usuarios for select using (auth.uid() = id);

drop policy if exists "dono ve todos os perfis" on public.usuarios;
create policy "dono ve todos os perfis"
on public.usuarios for select to authenticated
using (public.usuario_e_dono());

drop policy if exists "usuario atualiza o proprio perfil" on public.usuarios;
create policy "usuario atualiza o proprio perfil"
on public.usuarios for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "usuarios veem escolas cadastradas" on public.escolas;
create policy "usuarios veem escolas cadastradas"
on public.escolas for select to authenticated using (true);
drop policy if exists "dono cadastra escolas" on public.escolas;
create policy "dono cadastra escolas"
on public.escolas for insert to authenticated
with check (public.usuario_e_dono());

drop policy if exists "dono autoriza usuarios" on public.usuarios;
create policy "dono autoriza usuarios"
on public.usuarios for update to authenticated
using (public.usuario_e_dono())
with check (papel in ('aluno', 'professor', 'gestor_escola', 'dono'));

create or replace function public.proteger_conta_dono()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if old.papel = 'dono' and (new.papel <> 'dono' or new.autorizado = false) then
    raise exception 'A conta do dono nao pode ser rebaixada';
  end if;
  return new;
end;
$$;

drop trigger if exists proteger_conta_dono on public.usuarios;
create trigger proteger_conta_dono before update on public.usuarios
for each row execute function public.proteger_conta_dono();

drop policy if exists "usuario gerencia o proprio progresso" on public.progresso;
create policy "usuario gerencia o proprio progresso"
on public.progresso for all using (auth.uid() = usuario_id) with check (auth.uid() = usuario_id);

drop policy if exists "usuario gerencia as proprias tarefas" on public.tarefas;
create policy "usuario gerencia as proprias tarefas"
on public.tarefas for all using (auth.uid() = usuario_id) with check (auth.uid() = usuario_id);

alter table public.aulas_customizadas enable row level security;
alter table public.tarefas_customizadas enable row level security;
alter table public.comentarios enable row level security;

drop policy if exists "conteudo customizado visivel para usuarios" on public.aulas_customizadas;
create policy "conteudo customizado visivel para usuarios"
on public.aulas_customizadas for select to authenticated using (true);
drop policy if exists "professor cria aulas" on public.aulas_customizadas;
create policy "professor cria aulas"
on public.aulas_customizadas for insert to authenticated
with check (auth.uid() = professor_id and exists (select 1 from public.usuarios where id = auth.uid() and papel = 'professor' and autorizado = true));

drop policy if exists "tarefas customizadas visiveis para usuarios" on public.tarefas_customizadas;
create policy "tarefas customizadas visiveis para usuarios"
on public.tarefas_customizadas for select to authenticated using (true);
drop policy if exists "professor cria tarefas" on public.tarefas_customizadas;
create policy "professor cria tarefas"
on public.tarefas_customizadas for insert to authenticated
with check (auth.uid() = professor_id and exists (select 1 from public.usuarios where id = auth.uid() and papel = 'professor' and autorizado = true));

drop policy if exists "comentarios visiveis para usuarios" on public.comentarios;
create policy "comentarios visiveis para usuarios"
on public.comentarios for select to authenticated using (true);
drop policy if exists "aluno cria comentarios" on public.comentarios;
create policy "aluno cria comentarios"
on public.comentarios for insert to authenticated
with check (auth.uid() = aluno_id and exists (select 1 from public.usuarios where id = auth.uid() and papel = 'aluno'));

-- Depois de criar a primeira conta, o dono deve promovê-la manualmente uma vez:
-- update public.usuarios set papel = 'dono', autorizado = true where email = 'seu@email.com';

-- Usuario solicitado: crie-o com a senha escolhida em Authentication > Users.
-- Nunca coloque a senha neste arquivo ou no front-end.
